# Travis-CI script for the Application Lifecycle Deployment Engine
#
# This is being developed for the TANGO Project: http://tango-project.eu
#
# Copyright: David García Pérez, Atos Research and Innovation, 2016.
#
# This code is licensed under an Apache 2.0 license. Please, refer to the LICENSE.TXT file for more information

language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install pybuilder"

# command to compile and build tests
script: "pyb install_dependencies; pyb"
